"use client";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/store/store";
import Header from "@/components/Header";
import { useState } from "react";
import { useRouter } from "next/navigation";

const metadata = {
  title: "App Builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const { locale, locales, push } = useRouter();
  console.log("params from router", locale, locales);
  return (
    <html lang={params.lang}>
      <body>
        <Provider store={store}>
          <div>{children}</div>
        </Provider>
      </body>
    </html>
  );
}
