"use client";
import "./globals.css";
import { Provider } from "react-redux";
import store from "../store/store";
import { Noto_Sans_Arabic } from "next/font/google";

const arabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-arabic",
  display: "swap",
});

const metadata = {
  title: "App Builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html
      lang={params.lang}
      className={params.lang === "ar" && arabic.className}
    >
      <body>
        <Provider store={store}>
          <div>{children}</div>
        </Provider>
      </body>
    </html>
  );
}
