"use client";
import "./globals.css";
import { Provider } from "react-redux";
import store from "../store/store";
import { Noto_Sans_Arabic, Inter } from "next/font/google";
import Head from "next/head";

const arabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-arabic",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-eng",
  display: "swap",
});

const metadata = {
  title: "Launch Swift",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html
      lang={params.lang}
      className={params.lang === "ar" ? arabic.className : inter.className}
    >
      <Head>
        <title>{metadata.title}</title>
      </Head>
      <body>
        <Provider store={store}>
          <div>{children}</div>
        </Provider>
      </body>
    </html>
  );
}
